#!/usr/bin/env python3
"""Exact algebra verifier for the two-step minimax resolution.

All calculations are over the explicit radical extension generated by sqrt(2)
and sqrt(9+8*sqrt(2)).  A successful run verifies the fixed-schedule PEP dual
identity and the radical identities used by the global elementary lower bound.
It is not a substitute for the quantified case argument in resolution.md.
"""

from __future__ import annotations

import json
import sympy as sp


def simp(x):
    return sp.simplify(sp.radsimp(x))


q = sp.sqrt(2)
t = sp.sqrt(9 + 8*q)
r = sp.Rational(2, 1) / (1 + t)
C = r**2 / 2
h1 = q
h2 = 1 + r*(1 + q)
H = (r**-2 - 1) / 2
u0 = q - 1
v0 = r*(1 + q)


def assert_zero(x, label):
    z = simp(x)
    if z != 0:
        raise AssertionError(f"{label}: {z}")


# Radical and boundary identities.
assert_zero(h2 - (3+t)/4, "second step")
assert_zero(C - 1/(5+4*q+t), "constant")
assert_zero(H - (h1+h2), "Huber sum threshold")
assert_zero(u0*v0-r, "quadratic boundary")
assert_zero(v0-r*(u0+2), "right-capped boundary")
assert sp.ask(sp.Q.positive(r)) and float(r) < 1


# Four-sample interpolation matrices. Vector order is (x0,g0,g1,g2),
# sample order is (*,0,1,2), and Q_ij is the directed inequality i <- j.
eye = sp.eye(4)
zero4 = sp.zeros(4, 1)
pos = (
    zero4,
    eye[:, 0],
    eye[:, 0] - h1*eye[:, 1],
    eye[:, 0] - h1*eye[:, 1] - h2*eye[:, 2],
)
grad = (zero4, eye[:, 1], eye[:, 2], eye[:, 3])
fcoord = (sp.zeros(3, 1), sp.eye(3)[:, 0], sp.eye(3)[:, 1], sp.eye(3)[:, 2])
edges = tuple((i, j) for i in range(4) for j in range(4) if i != j)


def sym_outer(a, b):
    return (a*b.T + b*a.T)/2


avec, amat = {}, {}
for i, j in edges:
    dg = grad[i]-grad[j]
    avec[i, j] = fcoord[i]-fcoord[j]
    amat[i, j] = -sym_outer(grad[j], pos[i]-pos[j]) - dg*dg.T/2


lam = {edge: sp.S.Zero for edge in edges}
lam[0, 1] = q*r**2
lam[0, 2] = (2+q)*r**2
lam[0, 3] = r
lam[1, 2] = (1+q)*r**2
lam[2, 1] = r**2
lam[2, 3] = 1-r

# Exact coefficient balance: sum lambda Q_ij contributes -f2.
fbalance = sum((lam[e]*avec[e] for e in edges), sp.zeros(3, 1))
for k, expected in enumerate((0, 0, -1)):
    assert_zero(fbalance[k]-expected, f"function balance {k}")

E00 = sp.zeros(4); E00[0, 0] = 1
S = C*E00 - sum((lam[e]*amat[e] for e in edges), sp.zeros(4))
w = sp.Matrix([r/q, -r, -r*(1+q), -1/q])
for i in range(4):
    for j in range(4):
        assert_zero(S[i, j]-w[i]*w[j], f"PSD entry {i},{j}")


# Exact equality witnesses at the claimed schedule.
hub = 1/(1+2*(h1+h2))
hub_value = 1/(2*(1+2*(h1+h2)))
quad_value = ((1-h1)*(1-h2))**2/2
right_cap_value = ((h2-1)/(1+h1))**2/2
for label, value in (
    ("Huber", hub_value),
    ("quadratic", quad_value),
    ("right-capped quadratic", right_cap_value),
):
    assert_zero(value-C, f"{label} equality value")
assert_zero(hub-r**2, "Huber delta")


# Positivity is transparent in this parametrization except for 1-r; the latter
# follows from t>1, hence 0<r=2/(1+t)<1.
assert_zero((2+q)*r**2 - (1-r-q*r**2), "alternate lambda *<-1")

result = {
    "status": "exact verification passed",
    "field_generators": ["sqrt(2)", "sqrt(9+8*sqrt(2))"],
    "r": str(r),
    "C": str(C),
    "h1": str(h1),
    "h2": str(h2),
    "positive_dual_support": {
        "*<-0": str(lam[0, 1]),
        "*<-1": str(lam[0, 2]),
        "*<-2": str(lam[0, 3]),
        "0<-1": str(lam[1, 2]),
        "1<-0": str(lam[2, 1]),
        "1<-2": str(lam[2, 3]),
    },
    "dual_psd_factor": [str(x) for x in w],
    "checked": [
        "original radical schedule and constant",
        "three-variable function-value balance",
        "all sixteen entries S = w*w^T",
        "Huber, quadratic, and right-capped equality values",
        "global-case boundary identities H=h1+h2 and u0*v0=r",
    ],
}
print(json.dumps(result, indent=2))
