#!/usr/bin/env python3
"""Independent exact exhaustive checker using dual Newton inequalities.

For A contained in N^3,

    u in conv(A)+R^3_+ iff w.u >= min_{a in A} w.a for every w in R^3_+.

The hyperplanes w_k=0 and w.(a_i-a_j)=0 subdivide the nonnegative orthant
into rational polyhedral cones on each of which the minimum is one fixed
linear form.  Every extreme ray of every such cone is the intersection of two
of those hyperplanes.  We therefore take exact integer cross products of every
pair of their normals, retain the nonnegative rays, and test the displayed
inequality.  This is independent of the primal lambda feasibility algorithm in
enumerate_lp.py.
"""

from __future__ import annotations

import argparse
import json
import math
from collections import Counter
from itertools import combinations, product
from pathlib import Path


Exponent = tuple[int, int, int]
Generators = tuple[Exponent, ...]


def dot(left: Exponent, right: Exponent) -> int:
    return sum(left[k] * right[k] for k in range(3))


def cross(left: Exponent, right: Exponent) -> Exponent:
    return (
        left[1] * right[2] - left[2] * right[1],
        left[2] * right[0] - left[0] * right[2],
        left[0] * right[1] - left[1] * right[0],
    )


def primitive_nonnegative(vector: Exponent) -> Exponent | None:
    if vector == (0, 0, 0):
        return None
    if all(entry <= 0 for entry in vector):
        vector = tuple(-entry for entry in vector)  # type: ignore[assignment]
    if not all(entry >= 0 for entry in vector):
        return None
    divisor = math.gcd(*vector)
    return tuple(entry // divisor for entry in vector)  # type: ignore[return-value]


def dual_rays(generators: Generators) -> tuple[Exponent, ...]:
    boundaries: list[Exponent] = [(1, 0, 0), (0, 1, 0), (0, 0, 1)]
    boundaries.extend(
        tuple(generators[i][k] - generators[j][k] for k in range(3))
        for i, j in combinations(range(len(generators)), 2)
    )
    rays: set[Exponent] = set()
    for left, right in combinations(boundaries, 2):
        candidate = primitive_nonnegative(cross(left, right))
        if candidate is not None:
            rays.add(candidate)
        candidate = primitive_nonnegative(tuple(-entry for entry in cross(left, right)))
        if candidate is not None:
            rays.add(candidate)
    # Coordinate axes are also generated by pairs of coordinate boundaries;
    # retain this explicit assertion as a guard on the construction.
    assert {(1, 0, 0), (0, 1, 0), (0, 0, 1)} <= rays
    return tuple(sorted(rays))


def in_integral_closure(generators: Generators, exponent: Exponent) -> bool:
    return all(
        dot(ray, exponent) >= min(dot(ray, generator) for generator in generators)
        for ray in dual_rays(generators)
    )


def in_monomial_ideal(generators: Generators, exponent: Exponent) -> bool:
    for generator in generators:
        divides = True
        for coordinate in range(3):
            if generator[coordinate] > exponent[coordinate]:
                divides = False
                break
        if divides:
            return True
    return False


def admissible_ideals() -> list[Generators]:
    """A separately written enumeration of the labeled parameter tuples."""

    answer: list[Generators] = []
    for powers in product((1, 2, 3, 4), repeat=3):
        a, b, c = powers
        axes: Generators = ((a, 0, 0), (0, b, 0), (0, 0, c))
        answer.append(axes)
        candidates = product(range(a), range(b), range(c))
        for candidate in candidates:
            positive_support = [entry for entry in candidate if entry != 0]
            if len(positive_support) >= 2 and sum(candidate) <= 4:
                answer.append(axes + (candidate,))
    assert sum(len(item) == 3 for item in answer) == 64
    assert sum(len(item) == 4 for item in answer) == 453
    assert len(answer) == len({tuple(item) for item in answer}) == 517
    return answer


def expected_socle_of_input(generators: Generators) -> list[Exponent]:
    """Closed-form socle, independent of exhaustive neighbor testing."""

    a, b, c = generators[0][0], generators[1][1], generators[2][2]
    if len(generators) == 3:
        return [(a - 1, b - 1, c - 1)]
    mixed = generators[3]
    answer: list[Exponent] = []
    for coordinate in range(3):
        if mixed[coordinate] == 0:
            continue
        point = [a - 1, b - 1, c - 1]
        point[coordinate] = mixed[coordinate] - 1
        answer.append(tuple(point))
    return answer


def analyze(generators: Generators) -> dict[str, object]:
    bounds = (generators[0][0], generators[1][1], generators[2][2])
    points = list(product(*(range(bound + 1) for bound in bounds)))
    direct_bits: list[str] = []
    closure_bits: list[str] = []
    closure_lookup: dict[Exponent, bool] = {}
    for point in points:
        direct_bits.append("1" if in_monomial_ideal(generators, point) else "0")
        membership = in_integral_closure(generators, point)
        closure_lookup[point] = membership
        closure_bits.append("1" if membership else "0")

    socle_i = expected_socle_of_input(generators)
    # A second v-number route: construct the finite standard down-set and take
    # all of its globally maximal elements, rather than testing three neighbors.
    standard = [
        point
        for point in product(*(range(bound) for bound in bounds))
        if not closure_lookup[point]
    ]
    socle_closed = [
        point
        for point in standard
        if not any(
            point != other
            and all(point[k] <= other[k] for k in range(3))
            for other in standard
        )
    ]
    assert socle_i and socle_closed
    return {
        "generators": [list(generator) for generator in generators],
        "bounds": list(bounds),
        "grid_order": "lexicographic product(range(a+1),range(b+1),range(c+1))",
        "ideal_membership_bits": "".join(direct_bits),
        "closure_membership_bits": "".join(closure_bits),
        "socle_I": [list(point) for point in socle_i],
        "socle_closure": [list(point) for point in socle_closed],
        "v_I": min(map(sum, socle_i)),
        "v_closure": min(map(sum, socle_closed)),
    }


def build_payload() -> dict[str, object]:
    ideals = admissible_ideals()
    records = [analyze(generators) for generators in ideals]
    differences = Counter(
        record["v_closure"] - record["v_I"]  # type: ignore[operator]
        for record in records
    )
    control_generators: Generators = (
        (2, 0, 0),
        (0, 2, 0),
        (0, 0, 5),
        (1, 1, 1),
    )
    control = analyze(control_generators)
    assert (control["v_I"], control["v_closure"]) == (2, 3)
    assert all(record["v_closure"] <= record["v_I"] for record in records)
    return {
        "method": "exact-integer-dual-cone-rays-and-global-maximal-standard-points",
        "arithmetic": "integers only; no floating point",
        "labeled_ideal_count": len(records),
        "three_generator_count": sum(len(generators) == 3 for generators in ideals),
        "four_generator_count": sum(len(generators) == 4 for generators in ideals),
        "expanded_grid_point_count": sum(
            (record["bounds"][0] + 1)  # type: ignore[index,operator]
            * (record["bounds"][1] + 1)  # type: ignore[index,operator]
            * (record["bounds"][2] + 1)  # type: ignore[index,operator]
            for record in records
        ),
        "standard_box_point_count": sum(
            record["bounds"][0]  # type: ignore[index]
            * record["bounds"][1]  # type: ignore[index]
            * record["bounds"][2]  # type: ignore[index]
            for record in records
        ),
        "v_closure_minus_v_I_distribution": {
            str(key): differences[key] for key in sorted(differences)
        },
        "violating_count": sum(
            record["v_closure"] > record["v_I"] for record in records
        ),
        "degree_five_positive_control": control,
        "records": records,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("output", type=Path)
    args = parser.parse_args()
    payload = build_payload()
    args.output.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2, sort_keys=True) + "\n",
        encoding="utf-8",
    )
    print(
        json.dumps(
            {key: value for key, value in payload.items() if key != "records"},
            ensure_ascii=False,
            sort_keys=True,
        )
    )


if __name__ == "__main__":
    main()
