#!/Users/mac/4prove-or-disprove-math/.research-venv/bin/python
"""Independent exact replay of the mixed (20,8,7) Farkas certificate.

This verifier deliberately does not import the discovery matrix generator or
the certificate builder.  It reconstructs Definition 5.1 from the frozen
problem statement.  Its degree-20 Hadamard coefficient matrix is generated by
a target-coefficient recurrence which removes the *last* nonzero source
exponent; the discovery generator removes the first exponent and scatters
source columns.  All matrix entries are signed 64-bit integers (their absolute
column sum is at most 4**20), while certificate accumulation uses Python
arbitrary-precision integers.
"""

from __future__ import annotations

import hashlib
import json
import math
from pathlib import Path

import numpy as np


N = 20
K = 8
D = 7
QK = 1 << K
QDUAL = 1 << (N - K)
SCALE = 1 << N
H = np.array(
    [[1, 1, 1, 1], [1, 1, -1, -1],
     [1, -1, 1, -1], [1, -1, -1, 1]],
    dtype=np.int64,
)
CERT = Path("evidence/mixed_d7_farkas.json")
REPORT = Path("evidence/mixed_d7_farkas_verification.json")


def compositions(degree: int) -> list[tuple[int, int, int, int]]:
    return [
        (a, b, c, degree - a - b - c)
        for a in range(degree + 1)
        for b in range(degree - a + 1)
        for c in range(degree - a - b + 1)
    ]


def independent_hadamard_matrix() -> tuple[list[tuple[int, int, int, int]], np.ndarray]:
    """Generate T[t,s]=[x^t] product_i (H_i x)^s_i exactly.

    For each source exponent s, remove its last nonzero coordinate i.  The
    coefficient at t is then sum_j H[i,j] times the parent coefficient at
    t-e_j.  This computes every one of the 1771**2 degree-20 coefficients.
    """
    previous_index = [(0, 0, 0, 0)]
    previous = np.ones((1, 1), dtype=np.int64)
    for degree in range(1, N + 1):
        current_index = compositions(degree)
        previous_position = {s: q for q, s in enumerate(previous_index)}

        # gather[j][t] is the degree-(d-1) row for t-e_j, or -1.
        gather: list[np.ndarray] = []
        valid: list[np.ndarray] = []
        for j in range(4):
            g = np.full(len(current_index), -1, dtype=np.int32)
            for ti, t in enumerate(current_index):
                if t[j]:
                    parent = list(t)
                    parent[j] -= 1
                    g[ti] = previous_position[tuple(parent)]
            gather.append(g)
            valid.append(np.flatnonzero(g >= 0))

        current = np.zeros((len(current_index), len(current_index)), dtype=np.int64)
        for si, source in enumerate(current_index):
            i = max(q for q, exponent in enumerate(source) if exponent)
            parent = list(source)
            parent[i] -= 1
            parent_column = previous_position[tuple(parent)]
            for j in range(4):
                target_rows = valid[j]
                current[target_rows, si] += (
                    H[i, j] * previous[gather[j][target_rows], parent_column]
                )
        previous_index, previous = current_index, current
    return previous_index, previous


def krawtchouk(j: int, w: int) -> int:
    lo = max(0, j - (N - w))
    hi = min(j, w)
    return sum(
        (-1) ** ell * math.comb(w, ell) * math.comb(N - w, j - ell)
        for ell in range(lo, hi + 1)
    )


def exact_rows(index: list[tuple[int, int, int, int]], distance: int = D):
    """Return the independently generated canonical equality row descriptors."""
    position = {s: q for q, s in enumerate(index)}
    m0 = 2 * (N + 1)
    rows: list[tuple[str, dict[int, int] | None, int, int | None]] = []

    def avar(w: int) -> int:
        return w

    def bvar(w: int) -> int:
        return N + 1 + w

    def mvar(s: tuple[int, int, int, int]) -> int:
        return m0 + position[s]

    def add(name: str, coefficients: dict[int, int], rhs: int) -> None:
        clean = {j: int(v) for j, v in coefficients.items() if v}
        rows.append((name, clean, int(rhs), None))

    add("A0", {avar(0): 1}, 1)
    add("B0", {bvar(0): 1}, 1)
    for w in range(1, distance):
        add(f"A_zero[{w}]", {avar(w): 1}, 0)
    for j in range(N + 1):
        coefficients = {bvar(j): QK}
        for w in range(N + 1):
            coefficients[avar(w)] = -krawtchouk(j, w)
        add(f"hamming_MacWilliams[{j}]", coefficients, 0)

    for s in index:
        a, b, c, e = s
        if e % 2 == 1:
            add(f"M_even[{a},{b},{c},{e}]", {mvar(s): 1}, 0)
        if 1 <= c + e < distance:
            add(f"M_distance[{a},{b},{c},{e}]", {mvar(s): 1}, 0)
        if b == 0 and c == 0 and e > 0:
            add(f"M_diagonal_axis[{a},0,0,{e}]", {mvar(s): 1}, 0)

    for w in range(N + 1):
        add(
            f"B_axis[{w}]",
            {mvar((N - w, w, 0, 0)): 1, bvar(w): -1},
            0,
        )
        add(
            f"A_axis[{w}]",
            {mvar((N - w, 0, w, 0)): 1, avar(w): -1},
            0,
        )
        coefficients = {avar(w): -QDUAL}
        for s in index:
            if s[2] + s[3] == w:
                coefficients[mvar(s)] = 1
        add(f"A_marginal[{w}]", coefficients, 0)

        coefficients = {bvar(w): -QK}
        for s in index:
            if s[1] + s[3] == w:
                coefficients[mvar(s)] = 1
        add(f"B_marginal[{w}]", coefficients, 0)

        coefficients = {}
        for s in index:
            if s[1] + s[2] == w:
                coefficients[mvar(s)] = 1
        add(f"binomial_marginal[{w}]", coefficients, math.comb(N, w))

    # Joint rows are stored by target index; every coefficient is in T below.
    for ti, target in enumerate(index):
        name = f"joint_MacWilliams[{','.join(map(str, target))}]"
        rows.append((name, None, 0, ti))
    return rows, m0


def scaled_integer(pair: list[int], common_denominator: int) -> int:
    if not isinstance(pair, list) or len(pair) != 2:
        raise AssertionError(f"malformed rational: {pair!r}")
    numerator, denominator = pair
    if not isinstance(numerator, int) or not isinstance(denominator, int) or denominator <= 0:
        raise AssertionError(f"malformed rational: {pair!r}")
    if common_denominator % denominator:
        raise AssertionError("certificate denominator does not divide the common denominator")
    return numerator * (common_denominator // denominator)


def main() -> None:
    raw = CERT.read_bytes()
    certificate = json.loads(raw)
    if certificate.get("format") != "mixed-d7-farkas-v1":
        raise AssertionError("unexpected certificate format")
    if certificate.get("parameters") != {"n": N, "k": K, "d": D}:
        raise AssertionError("wrong certificate parameters")

    index, transform = independent_hadamard_matrix()
    rows, m0 = exact_rows(index)
    variable_count = m0 + len(index)
    if transform.shape != (len(index), len(index)):
        raise AssertionError("incomplete joint transform")
    if len(index) != 1771 or variable_count != 1813 or len(rows) != 3205:
        raise AssertionError("unexpected exact-system dimensions")

    # Cheap global identities test every transform column.  Evaluation at
    # (1,1,1,1) is 4**20 only for source (20,0,0,0), and zero otherwise;
    # collecting like terms can only decrease the pre-collection l1 norm
    # 4**20.  The x0**20 coefficient is one for every source monomial.
    column_sums = transform.sum(axis=0, dtype=np.int64)
    expected_sums = np.zeros(len(index), dtype=np.int64)
    expected_sums[index.index((N, 0, 0, 0))] = 4 ** N
    if not np.array_equal(column_sums, expected_sums):
        raise AssertionError("Hadamard transform all-ones evaluation identity failed")
    absolute_column_sums = np.abs(transform).sum(axis=0, dtype=np.int64)
    if np.any(absolute_column_sums > 4 ** N):
        raise AssertionError("Hadamard transform l1 bound failed")
    x0_row = index.index((N, 0, 0, 0))
    if not np.all(transform[x0_row, :] == 1):
        raise AssertionError("Hadamard transform x0^20-row identity failed")

    denominator = certificate["common_dyadic_denominator"]
    if not isinstance(denominator, int) or denominator <= 0:
        raise AssertionError("invalid common denominator")

    y = [0] * len(rows)
    seen_rows: set[int] = set()
    for item in certificate["equality_multipliers"]:
        ri = item["row"]
        if not isinstance(ri, int) or not (0 <= ri < len(rows)) or ri in seen_rows:
            raise AssertionError(f"invalid or duplicate equality row {ri!r}")
        seen_rows.add(ri)
        if item["name"] != rows[ri][0]:
            raise AssertionError(f"row-name mismatch at {ri}")
        y[ri] = scaled_integer(item["value"], denominator)

    coefficients = [0] * variable_count
    rhs_numerator = 0
    for yi, (_, sparse_row, rhs, target_index) in zip(y, rows):
        if yi == 0:
            continue
        rhs_numerator += yi * rhs
        if sparse_row is not None:
            for variable, value in sparse_row.items():
                coefficients[variable] += yi * value
        else:
            assert target_index is not None
            row = transform[target_index]
            for source_index, value in enumerate(row):
                if value:
                    coefficients[m0 + source_index] -= yi * int(value)
            coefficients[m0 + target_index] += yi * SCALE

    if certificate.get("packing_multipliers") != []:
        raise AssertionError("this certificate was expected to use zero packing multipliers")

    listed_lower = [0] * variable_count
    seen_variables: set[int] = set()
    for item in certificate["lower_bound_multipliers"]:
        variable = item["variable"]
        if (
            not isinstance(variable, int)
            or not (0 <= variable < variable_count)
            or variable in seen_variables
        ):
            raise AssertionError(f"invalid or duplicate lower-bound variable {variable!r}")
        seen_variables.add(variable)
        listed_lower[variable] = scaled_integer(item["value"], denominator)

    if coefficients != listed_lower:
        mismatch = next(i for i, (a, b) in enumerate(zip(coefficients, listed_lower)) if a != b)
        raise AssertionError(
            f"coefficient cancellation failed at variable {mismatch}: "
            f"recomputed={coefficients[mismatch]}, listed={listed_lower[mismatch]}"
        )
    if min(coefficients) < 0:
        raise AssertionError("a lower-bound multiplier is negative")
    if rhs_numerator >= 0:
        raise AssertionError("the recomputed equality RHS dot is not negative")

    claimed_rhs = scaled_integer(certificate["rhs_dot"], denominator)
    if rhs_numerator != claimed_rhs:
        raise AssertionError("RHS dot does not match the certificate")
    if min(coefficients) != certificate["minimum_lower_numerator_over_common_denominator"]:
        raise AssertionError("reported minimum lower multiplier is wrong")

    expected_counts = {
        "equalities_total": len(rows),
        "variables_total": variable_count,
        "nonzero_equalities": sum(value != 0 for value in y),
        "positive_lower_multipliers": sum(value > 0 for value in coefficients),
    }
    if certificate["counts"] != expected_counts:
        raise AssertionError("reported certificate counts are wrong")

    transform_bytes = np.asarray(transform, dtype="<i8").tobytes(order="C")
    transform_digest = hashlib.sha256(transform_bytes).hexdigest()
    report = {
        "format": "mixed-d7-farkas-independent-verification-v1",
        "verdict": "pass",
        "certificate": str(CERT),
        "certificate_sha256": hashlib.sha256(raw).hexdigest(),
        "parameters": {"n": N, "k": K, "d": D},
        "generator": (
            "standalone reconstruction from problem.md; no import from the "
            "discovery generator or certificate builder"
        ),
        "exact_system": {
            "variables": variable_count,
            "compositions": len(index),
            "equalities": len(rows),
            "packing_inequalities": N,
            "joint_transform_shape": list(transform.shape),
            "joint_transform_entries_generated": int(transform.size),
            "joint_transform_int64_sha256": transform_digest,
            "joint_transform_max_abs": int(np.max(np.abs(transform))),
        },
        "certificate_checks": {
            "common_dyadic_denominator": denominator,
            "nonzero_equality_multipliers": sum(value != 0 for value in y),
            "lower_multipliers_replayed": len(seen_variables),
            "minimum_lower_numerator": min(coefficients),
            "all_lower_multipliers_nonnegative": True,
            "rhs_numerator": rhs_numerator,
            "rhs_denominator": denominator,
            "rhs_strictly_negative": True,
            "all_equality_row_indices_and_names_match": True,
            "all_variable_coefficients_cancel_exactly": True,
            "packing_multipliers_are_zero": True,
        },
        "conclusion": (
            "For every x>=0 satisfying E x=b, exact replay gives "
            "(E^T y)^T x>=0 but y^T b<0. Hence M_2(20,8,7) is empty."
        ),
    }
    REPORT.write_text(json.dumps(report, indent=2) + "\n")
    print(json.dumps(report, indent=2))


if __name__ == "__main__":
    main()
