#!/usr/bin/env python3
"""Independent exact audit of all ten-vertex tree principal cores.

No discovery or builder module is imported.  Free trees are generated by
leaf extension and deduplicated with an independently written AHU code.  The
source edge lists are matched to this independently generated isomorphism
set, rather than trusted by source indices, graph6 strings, or source AHU
codes.  Every algebraic predicate uses integers.
"""

from __future__ import annotations

import argparse
import hashlib
import itertools
import json
import random
from pathlib import Path
from typing import Sequence


RANK = 10
TARGET_NONCORE = 53
EXPECTED_FREE_COUNTS = [1, 1, 1, 2, 3, 6, 11, 23, 47, 106]
EXPECTED_ROOTED_COUNTS = [1, 1, 2, 4, 9, 20, 48, 115, 286, 719]
POPCOUNT16 = tuple(bin(value).count("1") for value in range(1 << 16))


def popcount(value: int) -> int:
    total = 0
    while value:
        total += POPCOUNT16[value & 0xFFFF]
        value >>= 16
    return total


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def neighbours(adjacency: Sequence[Sequence[int]], vertex: int) -> list[int]:
    return [index for index, value in enumerate(adjacency[vertex]) if value]


def rooted_code(adjacency: Sequence[Sequence[int]], root: int, parent: int) -> str:
    branches = [
        rooted_code(adjacency, child, root)
        for child in neighbours(adjacency, root)
        if child != parent
    ]
    return "(" + "".join(sorted(branches)) + ")"


def centres(adjacency: Sequence[Sequence[int]]) -> list[int]:
    n = len(adjacency)
    if n <= 2:
        return list(range(n))
    degree = [sum(row) for row in adjacency]
    alive = [True] * n
    leaves = [vertex for vertex, value in enumerate(degree) if value <= 1]
    remaining = n
    while remaining > 2:
        layer = leaves
        leaves = []
        remaining -= len(layer)
        for leaf in layer:
            alive[leaf] = False
            for vertex, value in enumerate(adjacency[leaf]):
                if value and alive[vertex]:
                    degree[vertex] -= 1
                    if degree[vertex] == 1:
                        leaves.append(vertex)
    return [vertex for vertex, value in enumerate(alive) if value]


def free_tree_code(adjacency: Sequence[Sequence[int]]) -> str:
    center = centres(adjacency)
    if len(center) == 1:
        return "C" + rooted_code(adjacency, center[0], -1)
    if len(center) != 2:
        raise ValueError("tree does not have one or two centres")
    left = rooted_code(adjacency, center[0], center[1])
    right = rooted_code(adjacency, center[1], center[0])
    left, right = sorted((left, right))
    return "D" + left + "/" + right


def extend_by_leaf(adjacency: Sequence[Sequence[int]], parent: int) -> list[list[int]]:
    n = len(adjacency)
    out = [list(map(int, row)) + [0] for row in adjacency]
    out.append([0] * (n + 1))
    out[parent][n] = 1
    out[n][parent] = 1
    return out


def generate_free_trees() -> tuple[dict[str, list[list[int]]], list[int], list[int]]:
    layer: dict[str, list[list[int]]] = {"C()": [[0]]}
    free_counts = [1]
    rooted_counts = [1]
    for order in range(2, RANK + 1):
        next_layer: dict[str, list[list[int]]] = {}
        for code in sorted(layer):
            adjacency = layer[code]
            for parent in range(order - 1):
                extended = extend_by_leaf(adjacency, parent)
                next_layer.setdefault(free_tree_code(extended), extended)
        layer = next_layer
        free_counts.append(len(layer))
        rooted_types = {
            rooted_code(adjacency, root, -1)
            for adjacency in layer.values()
            for root in range(order)
        }
        rooted_counts.append(len(rooted_types))
    if free_counts != EXPECTED_FREE_COUNTS:
        raise AssertionError("free-tree layer counts disagree with known sequence")
    if rooted_counts != EXPECTED_ROOTED_COUNTS:
        raise AssertionError("rooted-tree counts disagree with known sequence")
    return layer, free_counts, rooted_counts


def adjacency_from_edge_list(raw_edges: object) -> list[list[int]]:
    if not isinstance(raw_edges, list):
        raise ValueError("source edge list is not a list")
    adjacency = [[0] * RANK for _ in range(RANK)]
    seen: set[tuple[int, int]] = set()
    for edge in raw_edges:
        if not isinstance(edge, list) or len(edge) != 2:
            raise ValueError("malformed source edge")
        i, j = map(int, edge)
        if not (0 <= i < j < RANK) or (i, j) in seen:
            raise ValueError("invalid or duplicate source edge")
        seen.add((i, j))
        adjacency[i][j] = adjacency[j][i] = 1
    if len(seen) != RANK - 1:
        raise ValueError("source object does not have nine edges")
    reached = {0}
    stack = [0]
    while stack:
        vertex = stack.pop()
        for child in neighbours(adjacency, vertex):
            if child not in reached:
                reached.add(child)
                stack.append(child)
    if len(reached) != RANK:
        raise ValueError("source edge list is disconnected")
    return adjacency


def determinant(matrix: Sequence[Sequence[int]]) -> int:
    n = len(matrix)
    if any(len(row) != n for row in matrix):
        raise ValueError("determinant needs a square matrix")
    if n == 0:
        return 1
    work = [list(map(int, row)) for row in matrix]
    sign = 1
    previous = 1
    for column in range(n - 1):
        pivot_row = next((row for row in range(column, n) if work[row][column]), None)
        if pivot_row is None:
            return 0
        if pivot_row != column:
            work[column], work[pivot_row] = work[pivot_row], work[column]
            sign = -sign
        pivot = work[column][column]
        for i in range(column + 1, n):
            for j in range(column + 1, n):
                numerator = work[i][j] * pivot - work[i][column] * work[column][j]
                if column and numerator % previous:
                    raise ArithmeticError("inexact Bareiss division")
                work[i][j] = numerator // previous
            work[i][column] = 0
        previous = pivot
    return sign * work[-1][-1]


def minor(
    matrix: Sequence[Sequence[int]], deleted_row: int, deleted_column: int
) -> list[list[int]]:
    return [
        [int(value) for column, value in enumerate(row) if column != deleted_column]
        for row_index, row in enumerate(matrix)
        if row_index != deleted_row
    ]


def adjugate(matrix: Sequence[Sequence[int]]) -> list[list[int]]:
    n = len(matrix)
    return [
        [((-1) ** (i + j)) * determinant(minor(matrix, j, i)) for j in range(n)]
        for i in range(n)
    ]


def multiply(
    left: Sequence[Sequence[int]], right: Sequence[Sequence[int]]
) -> list[list[int]]:
    return [
        [sum(left[i][k] * right[k][j] for k in range(len(right))) for j in range(len(right[0]))]
        for i in range(len(left))
    ]


def form(left_mask: int, adj: Sequence[Sequence[int]], right_mask: int) -> int:
    total = 0
    left = left_mask
    while left:
        left_bit = left & -left
        i = left_bit.bit_length() - 1
        right = right_mask
        while right:
            right_bit = right & -right
            j = right_bit.bit_length() - 1
            total += adj[i][j]
            right ^= right_bit
        left ^= left_bit
    return total


def perfect_matching_count(adjacency: Sequence[Sequence[int]]) -> int:
    full = (1 << len(adjacency)) - 1

    def recurse(unmatched: int) -> int:
        if not unmatched:
            return 1
        first_bit = unmatched & -unmatched
        first = first_bit.bit_length() - 1
        remainder = unmatched ^ first_bit
        total = 0
        for neighbour in neighbours(adjacency, first):
            neighbour_bit = 1 << neighbour
            if remainder & neighbour_bit:
                total += recurse(remainder ^ neighbour_bit)
        return total

    return recurse(full)


def build_noncore_graph(
    core: Sequence[Sequence[int]], det: int, adj: Sequence[Sequence[int]]
) -> tuple[list[int], list[int], int, list[int]]:
    isotropic = [
        mask for mask in range(1, 1 << RANK) if form(mask, adj, mask) == 0
    ]
    core_masks = [
        sum(int(core[row][column]) << row for row in range(RANK))
        for column in range(RANK)
    ]
    if len(set(core_masks)) != RANK or 0 in core_masks:
        raise AssertionError("nonsingular core columns are not distinct/nonzero")
    if not set(core_masks).issubset(isotropic):
        raise AssertionError("a core column is not isotropic")
    for core_mask in core_masks:
        for mask in isotropic:
            if form(core_mask, adj, mask) not in (0, det):
                raise AssertionError("a core column is not universal")
    core_set = set(core_masks)
    profiles = [mask for mask in isotropic if mask not in core_set]
    graph = [0] * len(profiles)
    edges = 0
    for i, left in enumerate(profiles):
        for j in range(i):
            numerator = form(left, adj, profiles[j])
            if numerator in (0, det):
                graph[i] |= 1 << j
                graph[j] |= 1 << i
                edges += 1
    return profiles, graph, edges, core_masks


def cyclic_relabel(adjacency: Sequence[int], shift: int = 1) -> list[int]:
    n = len(adjacency)
    if n == 0:
        return []
    shift %= n
    old_for_new = [(new + shift) % n for new in range(n)]
    new_for_old = [0] * n
    for new, old in enumerate(old_for_new):
        new_for_old[old] = new
    out = [0] * n
    for new, old in enumerate(old_for_new):
        bits = adjacency[old]
        while bits:
            bit = bits & -bits
            old_neighbour = bit.bit_length() - 1
            out[new] |= 1 << new_for_old[old_neighbour]
            bits ^= bit
    return out


class TargetClique:
    def __init__(self, adjacency: Sequence[int], target: int):
        self.adjacency = list(adjacency)
        self.target = target
        self.calls = 0
        self.cardinality_prunes = 0
        self.colour_prunes = 0
        self.witness: list[int] | None = None

    def colour_order(self, candidates: int) -> tuple[list[int], list[int]]:
        order: list[int] = []
        bounds: list[int] = []
        residue = candidates
        colour = 0
        while residue:
            colour += 1
            independent = residue
            while independent:
                bit = independent & -independent
                vertex = bit.bit_length() - 1
                order.append(vertex)
                bounds.append(colour)
                residue ^= bit
                independent ^= bit
                independent &= ~self.adjacency[vertex]
        return order, bounds

    def search(self, depth: int, candidates: int) -> bool:
        self.calls += 1
        need = self.target - depth
        if need <= 0:
            self.witness = []
            return True
        if popcount(candidates) < need:
            self.cardinality_prunes += 1
            return False
        order, bounds = self.colour_order(candidates)
        for position in range(len(order) - 1, -1, -1):
            if depth + bounds[position] < self.target:
                self.colour_prunes += 1
                return False
            vertex = order[position]
            bit = 1 << vertex
            if not candidates & bit:
                continue
            if self.search(depth + 1, candidates & self.adjacency[vertex]):
                return True
            candidates ^= bit
        return False

    def solve(self) -> bool:
        return self.search(0, (1 << len(self.adjacency)) - 1)


def brute_maximum_clique(adjacency: Sequence[int]) -> int:
    best = 0
    for subset in range(1 << len(adjacency)):
        size = popcount(subset)
        if size <= best:
            continue
        residue = subset
        valid = True
        while residue:
            bit = residue & -residue
            vertex = bit.bit_length() - 1
            if (subset ^ bit) & ~adjacency[vertex]:
                valid = False
                break
            residue ^= bit
        if valid:
            best = size
    return best


def clique_engine_selftest() -> dict[str, object]:
    tested = 0

    def check(adjacency: list[int]) -> None:
        nonlocal tested
        omega = brute_maximum_clique(adjacency)
        for target in range(1, len(adjacency) + 2):
            if TargetClique(adjacency, target).solve() != (omega >= target):
                raise AssertionError("target clique engine disagrees with brute force")
        tested += 1

    exhaustive: dict[str, int] = {}
    for n in range(6):
        edges = list(itertools.combinations(range(n), 2))
        for code in range(1 << len(edges)):
            graph = [0] * n
            for edge_index, (i, j) in enumerate(edges):
                if (code >> edge_index) & 1:
                    graph[i] |= 1 << j
                    graph[j] |= 1 << i
            check(graph)
        exhaustive[str(n)] = 1 << len(edges)
    rng = random.Random(2026082703)
    for n in range(6, 10):
        edge_pairs = list(itertools.combinations(range(n), 2))
        for _ in range(100):
            graph = [0] * n
            for i, j in edge_pairs:
                if rng.randrange(2):
                    graph[i] |= 1 << j
                    graph[j] |= 1 << i
            check(graph)
    return {
        "status": "PASS",
        "graphs_tested": tested,
        "exhaustive_labelled_counts": exhaustive,
        "random_graphs_per_order_6_through_9": 100,
    }


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", type=Path, required=True)
    parser.add_argument("--expected-source-sha256", required=True)
    parser.add_argument("--output", type=Path, required=True)
    args = parser.parse_args()

    source_hash = sha256(args.source)
    if source_hash != args.expected_source_sha256:
        raise ValueError("source SHA-256 mismatch")
    source = json.loads(args.source.read_text(encoding="utf-8"))
    if source.get("schema_version") != 1:
        raise ValueError("unexpected source schema")
    if source.get("counterexample_candidate_found") is not False or source.get("candidate_path") is not None:
        raise ValueError("source top-level conclusion is inconsistent")
    if int(source.get("target_noncore_clique_size", -1)) != TARGET_NONCORE:
        raise ValueError("unexpected target size")

    generated, free_counts, rooted_counts = generate_free_trees()
    if source.get("free_tree_layer_count_self_check") != free_counts:
        raise ValueError("source free-tree count vector mismatch")
    if source.get("rooted_tree_count_self_check") != rooted_counts:
        raise ValueError("source rooted-tree count vector mismatch")
    records = source.get("records")
    if not isinstance(records, list) or len(records) != 106:
        raise ValueError("source does not contain 106 records")
    if source.get("all_106_trees_processed") is not True:
        raise ValueError("source does not claim complete tree processing")

    record_by_own_code: dict[str, dict[str, object]] = {}
    for expected_index, record in enumerate(records):
        if int(record.get("tree_index", -1)) != expected_index:
            raise ValueError("source tree indices are incomplete or reordered")
        adjacency = adjacency_from_edge_list(record.get("canonical_edge_list"))
        own_code = free_tree_code(adjacency)
        if own_code in record_by_own_code:
            raise ValueError("two source records are isomorphic")
        record_by_own_code[own_code] = record
    if set(record_by_own_code) != set(generated):
        raise ValueError("source edge lists do not match the independently generated 106 trees")

    selftest = clique_engine_selftest()
    verified_records: list[dict[str, object]] = []
    nonsingular = 0
    total_calls = 0
    for position, own_code in enumerate(sorted(generated), 1):
        core = generated[own_code]
        record = record_by_own_code[own_code]
        det = determinant(core)
        matching_count = perfect_matching_count(core)
        if det != -(matching_count ** 2):
            raise AssertionError("tree determinant/perfect-matching identity failed")
        if det != int(record.get("determinant", 10**9)):
            raise ValueError("independent determinant disagrees with source")
        singular = det == 0
        if singular != bool(record.get("singular")):
            raise ValueError("independent singularity disagrees with source")
        print(f"VERIFY TREE {position}/106 source_index={record['tree_index']} singular={singular}", flush=True)
        if singular:
            verified_records.append({
                "independent_canonical_code": own_code,
                "source_tree_index": record["tree_index"],
                "determinant": 0,
                "perfect_matching_count": matching_count,
                "singular": True,
                "status": "PASS",
            })
            continue

        nonsingular += 1
        adj = adjugate(core)
        expected = [[det * int(i == j) for j in range(RANK)] for i in range(RANK)]
        if multiply(core, adj) != expected or multiply(adj, core) != expected:
            raise AssertionError("adjugate identities failed")
        profiles, graph, edges, core_masks = build_noncore_graph(core, det, adj)
        if len(profiles) != int(record.get("noncore_isotropic_count", -1)):
            raise ValueError("noncore profile count mismatch")
        if edges != int(record.get("compatibility_edge_count", -1)):
            raise ValueError("compatibility edge count mismatch")
        relabelled = cyclic_relabel(graph, 1)
        solver = TargetClique(relabelled, TARGET_NONCORE)
        found = solver.solve()
        if found:
            raise ValueError("independent search found a forbidden 53-profile clique")
        if record.get("target_clique_found") is not False:
            raise ValueError("source target-clique conclusion mismatch")
        total_calls += solver.calls
        verified_records.append({
            "independent_canonical_code": own_code,
            "source_tree_index": record["tree_index"],
            "source_ahu_canonical_code": record.get("ahu_canonical_code"),
            "determinant": det,
            "perfect_matching_count": matching_count,
            "singular": False,
            "noncore_isotropic_count": len(profiles),
            "compatibility_edge_count": edges,
            "core_masks": core_masks,
            "cyclic_relabel_shift": 1,
            "target_noncore_clique_size": TARGET_NONCORE,
            "target_clique_found": False,
            "independent_search_calls": solver.calls,
            "independent_search_cardinality_prunes": solver.cardinality_prunes,
            "independent_search_colour_prunes": solver.colour_prunes,
            "status": "PASS",
        })

    if nonsingular != 15 or nonsingular != int(source.get("nonsingular_tree_cores_processed", -1)):
        raise ValueError("nonsingular tree count is not 15")
    payload = {
        "schema": "reduced-graph-rank10.tree-core-family-independent-audit.v1",
        "status": "PASS",
        "source": str(args.source),
        "source_sha256": source_hash,
        "arithmetic": "integers only; Bareiss determinants and integer adjugates",
        "tree_generation": "independent leaf extension deduplicated by independent AHU center code",
        "free_tree_layer_counts": free_counts,
        "rooted_tree_counts_from_all_vertex-rootings": rooted_counts,
        "source_edge_lists_match_independent_isomorphism_set": True,
        "trees_verified": len(verified_records),
        "nonsingular_trees": nonsingular,
        "singular_trees": len(verified_records) - nonsingular,
        "nonsingular_tree_characterization": "exactly one perfect matching; det=-1",
        "all_nonsingular_cores_exclude_noncore_clique_size": TARGET_NONCORE,
        "independent_search_total_calls": total_calls,
        "search_engine": "cyclically relabelled exact target search with greedy proper-colour upper bounds",
        "search_engine_selftest": selftest,
        "counterexample_found": False,
        "records": verified_records,
    }
    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(json.dumps(payload, indent=2, sort_keys=True) + "\n", encoding="utf-8")
    print(json.dumps({key: value for key, value in payload.items() if key != "records"}, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()
